pointquad:
	g++ point_quad_tree/Point.cpp point_quad_tree/Point.h point_quad_tree/Rectangle.h point_quad_tree/QuadTreeNode.h point_quad_tree/PointQuadTree.h point_quad_tree/main.cpp -o main && main
rtree:
	g++ rtree/main.cpp -o output -lSDL2
	g++ main.cpp -o output -lSDL2 && ./output